// src/schema-embed.prw — GERADO por scripts/gen-schema-embed.sh.
//
// NAO EDITE A MAO. A fonte da verdade e schema.sql; este arquivo so o
// carrega para dentro do executavel, porque no primeiro arranque o app tem
// que criar as proprias tabelas sem depender de shell nem de sqlite3.
// scripts/check.sh reprova se os dois sairem de sincronia.
#include "totvs.ch"

/*/{Protheus.doc} GcSchemaSQL
    Devolve o conteudo de schema.sql embutido no executavel.
    @type Function
    @author GesCon (gerado)
    @return cSQL, character, DDL completo, comandos separados por ';'
*/
User Function GcSchemaSQL()
    Local aLinhas := {}
    Local cSQL := ""
    Local nI := 0

    AAdd(aLinhas, "-- GesCon — schema v1. Convenção de exclusão lógica estilo Protheus")
    AAdd(aLinhas, "-- (R_E_C_N_O_/D_E_L_E_T_/R_E_C_D_E_L_), mesma que o AdvEditor usa.")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Tabela de metadados SX3 (títulos/tipos de coluna pro FWMBrowse).")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS SX3 (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    X3_ARQUIVO TEXT NOT NULL,")
    AAdd(aLinhas, "    X3_ORDEM  INTEGER NOT NULL,")
    AAdd(aLinhas, "    X3_CAMPO  TEXT NOT NULL,")
    AAdd(aLinhas, "    X3_TIPO   TEXT NOT NULL,")
    AAdd(aLinhas, "    X3_TAMANHO INTEGER NOT NULL,")
    AAdd(aLinhas, "    X3_DECIMAL INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    X3_QUICK  TEXT DEFAULT 'N',")
    AAdd(aLinhas, "    X3_VLADB  TEXT DEFAULT '',")
    AAdd(aLinhas, "    X3_TITULO TEXT")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS CON (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    CON_CODIGO TEXT NOT NULL,")
    AAdd(aLinhas, "    CON_NOME TEXT NOT NULL,")
    AAdd(aLinhas, "    CON_CPF TEXT,")
    AAdd(aLinhas, "    CON_EMAIL TEXT,")
    AAdd(aLinhas, "    CON_TEL TEXT")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS UNI (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    UNI_CODIGO TEXT NOT NULL UNIQUE,")
    AAdd(aLinhas, "    UNI_BLOCO TEXT,")
    AAdd(aLinhas, "    UNI_FRACAO REAL NOT NULL DEFAULT 0,")
    AAdd(aLinhas, "    UNI_CONDOMINO TEXT")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Vínculo unidade->condômino: UNI_CONDOMINO é texto livre na tela (sem")
    AAdd(aLinhas, "-- combo/lookup), então valida na borda do banco em vez de na UI. Rejeita")
    AAdd(aLinhas, "-- código que não existe (ou está excluído) em CON, tanto no Incluir quanto")
    AAdd(aLinhas, "-- no Alterar da tela de Unidades.")
    AAdd(aLinhas, "CREATE TRIGGER IF NOT EXISTS TRG_UNI_CONDOMINO_INS")
    AAdd(aLinhas, "BEFORE INSERT ON UNI")
    AAdd(aLinhas, "WHEN NEW.UNI_CONDOMINO IS NOT NULL AND TRIM(NEW.UNI_CONDOMINO) <> ''")
    AAdd(aLinhas, "BEGIN")
    AAdd(aLinhas, "    SELECT RAISE(ABORT, 'Condômino inexistente: cadastre o condômino antes de vincular a unidade.')")
    AAdd(aLinhas, "    WHERE NOT EXISTS (SELECT 1 FROM CON WHERE CON_CODIGO = NEW.UNI_CONDOMINO AND D_E_L_E_T_ = ' ');")
    AAdd(aLinhas, "END;")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TRIGGER IF NOT EXISTS TRG_UNI_CONDOMINO_UPD")
    AAdd(aLinhas, "BEFORE UPDATE OF UNI_CONDOMINO ON UNI")
    AAdd(aLinhas, "WHEN NEW.UNI_CONDOMINO IS NOT NULL AND TRIM(NEW.UNI_CONDOMINO) <> ''")
    AAdd(aLinhas, "BEGIN")
    AAdd(aLinhas, "    SELECT RAISE(ABORT, 'Condômino inexistente: cadastre o condômino antes de vincular a unidade.')")
    AAdd(aLinhas, "    WHERE NOT EXISTS (SELECT 1 FROM CON WHERE CON_CODIGO = NEW.UNI_CONDOMINO AND D_E_L_E_T_ = ' ');")
    AAdd(aLinhas, "END;")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS DES (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    DES_DESCR TEXT NOT NULL,")
    AAdd(aLinhas, "    DES_CATEG TEXT,")
    AAdd(aLinhas, "    DES_VALOR REAL NOT NULL DEFAULT 0,")
    AAdd(aLinhas, "    DES_COMPET TEXT NOT NULL,")
    AAdd(aLinhas, "    DES_DTLANC TEXT")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS COB (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    COB_UNIDADE TEXT NOT NULL,")
    AAdd(aLinhas, "    COB_COMPET TEXT NOT NULL,")
    AAdd(aLinhas, "    COB_VALOR REAL NOT NULL DEFAULT 0,")
    AAdd(aLinhas, "    COB_VENCTO TEXT,")
    AAdd(aLinhas, "    COB_STATUS TEXT NOT NULL DEFAULT 'pendente',")
    AAdd(aLinhas, "    COB_DTPAG TEXT")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Trava de Cobrança: valor, unidade, competência e vencimento só nascem")
    AAdd(aLinhas, "-- pelo Fechamento Mensal e nunca mudam depois — só Registrar Pagamento")
    AAdd(aLinhas, "-- (COB_STATUS/COB_DTPAG) toca o registro em diante. A tela de Cobranças é")
    AAdd(aLinhas, "-- um FWMBrowse cru (Incluir/Alterar/Excluir livres na UI), então a garantia")
    AAdd(aLinhas, "-- só existe se o banco a impuser.")
    AAdd(aLinhas, "CREATE TRIGGER IF NOT EXISTS TRG_COB_TRAVA_VALOR")
    AAdd(aLinhas, "BEFORE UPDATE OF COB_VALOR, COB_UNIDADE, COB_COMPET, COB_VENCTO ON COB")
    AAdd(aLinhas, "WHEN OLD.COB_VALOR <> NEW.COB_VALOR")
    AAdd(aLinhas, "    OR OLD.COB_UNIDADE <> NEW.COB_UNIDADE")
    AAdd(aLinhas, "    OR OLD.COB_COMPET <> NEW.COB_COMPET")
    AAdd(aLinhas, "    OR IFNULL(OLD.COB_VENCTO, '') <> IFNULL(NEW.COB_VENCTO, '')")
    AAdd(aLinhas, "BEGIN")
    AAdd(aLinhas, "    SELECT RAISE(ABORT, 'Cobrança travada: valor, unidade, competência e vencimento não podem ser alterados depois de criados pelo Fechamento. Use Registrar Pagamento para status e data.');")
    AAdd(aLinhas, "END;")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TRIGGER IF NOT EXISTS TRG_COB_TRAVA_EXCLUSAO")
    AAdd(aLinhas, "BEFORE UPDATE OF D_E_L_E_T_ ON COB")
    AAdd(aLinhas, "WHEN NEW.D_E_L_E_T_ = '*' AND OLD.D_E_L_E_T_ = ' '")
    AAdd(aLinhas, "BEGIN")
    AAdd(aLinhas, "    SELECT RAISE(ABORT, 'Cobrança não pode ser excluída: é gerada pelo Fechamento Mensal e faz parte do histórico contábil.');")
    AAdd(aLinhas, "END;")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS USR (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    USR_LOGIN TEXT NOT NULL,")
    AAdd(aLinhas, "    USR_SENHA TEXT NOT NULL,")
    AAdd(aLinhas, "    USR_PERFIL TEXT DEFAULT 'ADMIN'")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Tabelas de relatório (Plano 2): snapshot recalculado do zero (DELETE +")
    AAdd(aLinhas, "-- INSERT) toda vez que o relatório é aberto, mesmo padrão que")
    AAdd(aLinhas, "-- GcFecharMes já usa pra gravar Cobrança — FWMBrowse só sabe abrir uma")
    AAdd(aLinhas, "-- tabela física por alias (SELECT rowid ..., UPDATE/DELETE ... WHERE")
    AAdd(aLinhas, "-- rowid = ?), não dá pra apontar pra uma query parametrizada ou VIEW sem")
    AAdd(aLinhas, "-- rowid direto. Read-only por convenção, mas tecnicamente editável pela")
    AAdd(aLinhas, "-- mesma limitação já aceita na tela de Cobranças (ver ARQUITETURA.md).")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS RPT_INADIM (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    RIN_UNIDADE TEXT,")
    AAdd(aLinhas, "    RIN_COMPET TEXT,")
    AAdd(aLinhas, "    RIN_VALOR REAL,")
    AAdd(aLinhas, "    RIN_VENCTO TEXT,")
    AAdd(aLinhas, "    RIN_ATRASO INTEGER")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS RPT_EXTRATO (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    REX_COMPET TEXT,")
    AAdd(aLinhas, "    REX_VALOR REAL,")
    AAdd(aLinhas, "    REX_VENCTO TEXT,")
    AAdd(aLinhas, "    REX_STATUS TEXT,")
    AAdd(aLinhas, "    REX_DTPAG TEXT")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS RPT_DESCAT (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    RDC_CATEG TEXT,")
    AAdd(aLinhas, "    RDC_TOTAL REAL")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- GesCon — CFG_BOLETO: configuração do beneficiário para geração de boletos.")
    AAdd(aLinhas, "-- Uma única linha (estilo MV; INSERT/UPDATE direto).")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS CFG_BOLETO (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    CFG_BANCO TEXT NOT NULL DEFAULT '237',")
    AAdd(aLinhas, "    CFG_AGENCIA TEXT NOT NULL,")
    AAdd(aLinhas, "    CFG_CONTA TEXT NOT NULL,")
    AAdd(aLinhas, "    CFG_COBRT TEXT NOT NULL,")
    AAdd(aLinhas, "    CFG_CARTEIRA TEXT NOT NULL")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- GesCon — GCT_TOKEN: tokens temporários para acesso condômino.")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS GCT_TOKEN (")
    AAdd(aLinhas, "    TOKEN TEXT PRIMARY KEY,")
    AAdd(aLinhas, "    USR_LOGIN TEXT NOT NULL,")
    AAdd(aLinhas, "    CON_CODIGO TEXT NOT NULL,")
    AAdd(aLinhas, "    UNI_CODIGO TEXT NOT NULL,")
    AAdd(aLinhas, "    CRIPTADO TEXT NOT NULL,")
    AAdd(aLinhas, "    VALIDO_ATE TEXT NOT NULL,")
    AAdd(aLinhas, "    USADO INTEGER DEFAULT 0,")
    AAdd(aLinhas, "    TOK_PERFIL TEXT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- GesCon — RPT_COND_COBRANCAS: snapshot de cobranças filtrado por unidade")
    AAdd(aLinhas, "-- (para acesso read-only do condômino via portal).")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS RPT_COND_COBRANCAS (")
    AAdd(aLinhas, "    RCC_UNIDADE TEXT NOT NULL,")
    AAdd(aLinhas, "    RCC_COMPET TEXT NOT NULL,")
    AAdd(aLinhas, "    RCC_VALOR REAL,")
    AAdd(aLinhas, "    RCC_VENCTO TEXT,")
    AAdd(aLinhas, "    RCC_STATUS TEXT,")
    AAdd(aLinhas, "    RCC_DTPAG TEXT,")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ INTEGER DEFAULT 0")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 (títulos/tipos de coluna pro FWMBrowse — ver browseColumns")
    AAdd(aLinhas, "-- em pkg/vm/browse.go do AdvPP: sem essas linhas, o browse cai no fallback")
    AAdd(aLinhas, "-- de mostrar toda coluna física como texto, sem título amigável).")
    AAdd(aLinhas, "-- Limpa TUDO antes de reinserir: o SX3 e metadado, reconstruido por inteiro")
    AAdd(aLinhas, "-- por este arquivo. A lista de X3_ARQUIVO que existia aqui cobria 11 das 24")
    AAdd(aLinhas, "-- tabelas, entao cada bootstrap repetido duplicava as outras 13 -- o banco de")
    AAdd(aLinhas, "-- desenvolvimento chegou a ter 4 copias de cada coluna de AVISOS.")
    AAdd(aLinhas, "DELETE FROM SX3;")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('CON', 1, 'CON_CODIGO', 'C', 10, 0, 'Código'),")
    AAdd(aLinhas, "('CON', 2, 'CON_NOME',   'C', 60, 0, 'Nome'),")
    AAdd(aLinhas, "('CON', 3, 'CON_CPF',    'C', 14, 0, 'CPF'),")
    AAdd(aLinhas, "('CON', 4, 'CON_EMAIL',  'C', 60, 0, 'E-mail'),")
    AAdd(aLinhas, "('CON', 5, 'CON_TEL',    'C', 20, 0, 'Telefone'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('UNI', 1, 'UNI_CODIGO',    'C', 10, 0, 'Unidade'),")
    AAdd(aLinhas, "('UNI', 2, 'UNI_BLOCO',     'C', 10, 0, 'Bloco'),")
    AAdd(aLinhas, "('UNI', 3, 'UNI_FRACAO',    'N', 8,  4, 'Fração Ideal'),")
    AAdd(aLinhas, "('UNI', 4, 'UNI_CONDOMINO', 'C', 10, 0, 'Cód. Condômino'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('DES', 1, 'DES_DESCR',   'C', 80, 0, 'Descrição'),")
    AAdd(aLinhas, "('DES', 2, 'DES_CATEG',   'C', 30, 0, 'Categoria'),")
    AAdd(aLinhas, "('DES', 3, 'DES_VALOR',   'N', 14, 2, 'Valor'),")
    AAdd(aLinhas, "('DES', 4, 'DES_COMPET',  'C', 7,  0, 'Competência'),")
    AAdd(aLinhas, "('DES', 5, 'DES_DTLANC',  'C', 10, 0, 'Data Lançamento'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('COB', 1, 'COB_UNIDADE', 'C', 10, 0, 'Unidade'),")
    AAdd(aLinhas, "('COB', 2, 'COB_COMPET',  'C', 7,  0, 'Competência'),")
    AAdd(aLinhas, "('COB', 3, 'COB_VALOR',   'N', 14, 2, 'Valor'),")
    AAdd(aLinhas, "('COB', 4, 'COB_VENCTO',  'C', 10, 0, 'Vencimento'),")
    AAdd(aLinhas, "('COB', 5, 'COB_STATUS',  'C', 10, 0, 'Status'),")
    AAdd(aLinhas, "('COB', 6, 'COB_DTPAG',   'C', 10, 0, 'Data Pagamento'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('RPT_INADIM', 1, 'RIN_UNIDADE', 'C', 10, 0, 'Unidade'),")
    AAdd(aLinhas, "('RPT_INADIM', 2, 'RIN_COMPET',  'C', 7,  0, 'Competência'),")
    AAdd(aLinhas, "('RPT_INADIM', 3, 'RIN_VALOR',   'N', 14, 2, 'Valor'),")
    AAdd(aLinhas, "('RPT_INADIM', 4, 'RIN_VENCTO',  'C', 10, 0, 'Vencimento'),")
    AAdd(aLinhas, "('RPT_INADIM', 5, 'RIN_ATRASO',  'N', 5,  0, 'Dias de Atraso'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('RPT_EXTRATO', 1, 'REX_COMPET', 'C', 7,  0, 'Competência'),")
    AAdd(aLinhas, "('RPT_EXTRATO', 2, 'REX_VALOR',  'N', 14, 2, 'Valor'),")
    AAdd(aLinhas, "('RPT_EXTRATO', 3, 'REX_VENCTO', 'C', 10, 0, 'Vencimento'),")
    AAdd(aLinhas, "('RPT_EXTRATO', 4, 'REX_STATUS', 'C', 10, 0, 'Status'),")
    AAdd(aLinhas, "('RPT_EXTRATO', 5, 'REX_DTPAG',  'C', 10, 0, 'Data Pagamento'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('RPT_DESCAT', 1, 'RDC_CATEG', 'C', 30, 0, 'Categoria'),")
    AAdd(aLinhas, "('RPT_DESCAT', 2, 'RDC_TOTAL', 'N', 14, 2, 'Total');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- USR_PERFIL e TOK_PERFIL nasceram como ALTER TABLE ADD COLUMN. O SQLite nao")
    AAdd(aLinhas, "-- tem IF NOT EXISTS para ADD COLUMN, entao reaplicar o schema abortava com")
    AAdd(aLinhas, '-- "duplicate column name" -- e o bootstrap saia 1 sem que ninguem visse.')
    AAdd(aLinhas, "-- Agora as colunas moram no CREATE TABLE das proprias tabelas.")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para CFG_BOLETO")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('CFG_BOLETO', 1, 'CFG_BANCO',    'C',  4, 0, 'Código do Banco'),")
    AAdd(aLinhas, "('CFG_BOLETO', 2, 'CFG_AGENCIA',  'C', 10, 0, 'Agência'),")
    AAdd(aLinhas, "('CFG_BOLETO', 3, 'CFG_CONTA',    'C', 15, 0, 'Conta Corrente'),")
    AAdd(aLinhas, "('CFG_BOLETO', 4, 'CFG_COBRT',    'C', 15, 0, 'Carta/Cedente ou Convênio'),")
    AAdd(aLinhas, "('CFG_BOLETO', 5, 'CFG_CARTEIRA', 'C', 10, 0, 'Carteira');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para GCT_TOKEN")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('GCT_TOKEN', 1, 'TOKEN',      'C', 36, 0, 'Token'),")
    AAdd(aLinhas, "('GCT_TOKEN', 2, 'USR_LOGIN',  'C', 40, 0, 'Gerado por'),")
    AAdd(aLinhas, "('GCT_TOKEN', 3, 'CON_CODIGO', 'C', 10, 0, 'Condômino'),")
    AAdd(aLinhas, "('GCT_TOKEN', 4, 'UNI_CODIGO', 'C', 10, 0, 'Unidade'),")
    AAdd(aLinhas, "('GCT_TOKEN', 5, 'CRIPTADO',   'C', 19, 0, 'Criado em'),")
    AAdd(aLinhas, "('GCT_TOKEN', 6, 'VALIDO_ATE', 'C', 19, 0, 'Válido até'),")
    AAdd(aLinhas, "('GCT_TOKEN', 7, 'USADO',      'N',  1, 0, 'Usado');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para RPT_COND_COBRANCAS")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('RPT_COND_COBRANCAS', 1, 'RCC_UNIDADE', 'C', 10, 0, 'Unidade'),")
    AAdd(aLinhas, "('RPT_COND_COBRANCAS', 2, 'RCC_COMPET',  'C',  7, 0, 'Competência'),")
    AAdd(aLinhas, "('RPT_COND_COBRANCAS', 3, 'RCC_VALOR',   'N', 14, 2, 'Valor'),")
    AAdd(aLinhas, "('RPT_COND_COBRANCAS', 4, 'RCC_VENCTO',  'C', 10, 0, 'Vencimento'),")
    AAdd(aLinhas, "('RPT_COND_COBRANCAS', 5, 'RCC_STATUS',  'C', 10, 0, 'Status'),")
    AAdd(aLinhas, "('RPT_COND_COBRANCAS', 6, 'RCC_DTPAG',   'C', 10, 0, 'Data Pagamento');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para USR_PERFIL")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('USR', 3, 'USR_PERFIL', 'C', 20, 0, 'Perfil do Usuário');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- ============================================================================")
    AAdd(aLinhas, "-- Sistema Contábil em Partida Dupla (v2.0)")
    AAdd(aLinhas, "-- 6 tabelas para suportar lançamentos manuais + automáticos, rateio,")
    AAdd(aLinhas, "-- fechamento de período com validação D/C, e auditoria.")
    AAdd(aLinhas, "-- ============================================================================")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS PLANO_CONTAS (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    PLA_CODIGO TEXT UNIQUE NOT NULL,")
    AAdd(aLinhas, "    PLA_NOME TEXT NOT NULL,")
    AAdd(aLinhas, "    PLA_TIPO TEXT NOT NULL,")
    AAdd(aLinhas, "    PLA_ATIVO NUMERIC DEFAULT 1,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC,")
    AAdd(aLinhas, "    CHECK(PLA_TIPO IN ('ATIVO', 'PASSIVO', 'RECEITA', 'DESPESA'))")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_PLANO_CONTAS_ATIVO ON PLANO_CONTAS(PLA_ATIVO, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS REPARTICAO (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    REP_CODIGO TEXT UNIQUE NOT NULL,")
    AAdd(aLinhas, "    REP_NOME TEXT NOT NULL,")
    AAdd(aLinhas, "    REP_ATIVO NUMERIC DEFAULT 1,")
    AAdd(aLinhas, "    REP_DETALHE TEXT,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_REPARTICAO_ATIVO ON REPARTICAO(REP_ATIVO, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS EXERCICIO (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    EXE_CODIGO TEXT UNIQUE NOT NULL,")
    AAdd(aLinhas, "    EXE_INICIO DATE NOT NULL,")
    AAdd(aLinhas, "    EXE_FIM DATE NOT NULL,")
    AAdd(aLinhas, "    EXE_ATIVO NUMERIC DEFAULT 0,")
    AAdd(aLinhas, "    EXE_FECHADO NUMERIC DEFAULT 0,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_EXERCICIO_ATIVO ON EXERCICIO(EXE_ATIVO, EXE_FECHADO, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS LANCAMENTOS (")
    AAdd(aLinhas, "    LAN_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    LAN_DATA DATE NOT NULL,")
    AAdd(aLinhas, "    LAN_CONTA_DEB TEXT NOT NULL,")
    AAdd(aLinhas, "    LAN_CONTA_CRED TEXT NOT NULL,")
    AAdd(aLinhas, "    LAN_VALOR NUMERIC NOT NULL,")
    AAdd(aLinhas, "    LAN_DESCR TEXT,")
    AAdd(aLinhas, "    LAN_REFERENCIA NUMERIC,")
    AAdd(aLinhas, "    LAN_TIPO TEXT NOT NULL,")
    AAdd(aLinhas, "    LAN_DATA_HORA DATETIME,")
    AAdd(aLinhas, "    LAN_USUARIO TEXT,")
    AAdd(aLinhas, "    LAN_EXERCICIO TEXT NOT NULL,")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC,")
    AAdd(aLinhas, "    FOREIGN KEY(LAN_CONTA_DEB) REFERENCES PLANO_CONTAS(PLA_CODIGO),")
    AAdd(aLinhas, "    FOREIGN KEY(LAN_CONTA_CRED) REFERENCES PLANO_CONTAS(PLA_CODIGO),")
    AAdd(aLinhas, "    FOREIGN KEY(LAN_EXERCICIO) REFERENCES EXERCICIO(EXE_CODIGO),")
    AAdd(aLinhas, "    CHECK(LAN_VALOR > 0),")
    AAdd(aLinhas, "    CHECK(LAN_TIPO IN ('MANUAL', 'AUTOMATICO_DESPESA', 'AUTOMATICO_RATEIO')),")
    AAdd(aLinhas, "    CHECK(LAN_CONTA_DEB != LAN_CONTA_CRED)")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_LANCAMENTOS_EXERCICIO ON LANCAMENTOS(LAN_EXERCICIO, D_E_L_E_T_);")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_LANCAMENTOS_TIPO ON LANCAMENTOS(LAN_TIPO, D_E_L_E_T_);")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_LANCAMENTOS_REFERENCIA ON LANCAMENTOS(LAN_REFERENCIA, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS RATEIO_DETALHE (")
    AAdd(aLinhas, "    RAT_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    RAT_LANCAMENTO INTEGER NOT NULL,")
    AAdd(aLinhas, "    RAT_UNIDADE TEXT NOT NULL,")
    AAdd(aLinhas, "    RAT_VALOR NUMERIC NOT NULL,")
    AAdd(aLinhas, "    RAT_PERCENTUAL NUMERIC,")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC,")
    AAdd(aLinhas, "    FOREIGN KEY(RAT_LANCAMENTO) REFERENCES LANCAMENTOS(LAN_ID),")
    AAdd(aLinhas, "    FOREIGN KEY(RAT_UNIDADE) REFERENCES UNI(UNI_CODIGO),")
    AAdd(aLinhas, "    CHECK(RAT_VALOR > 0)")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_RATEIO_LANCAMENTO ON RATEIO_DETALHE(RAT_LANCAMENTO, D_E_L_E_T_);")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_RATEIO_UNIDADE ON RATEIO_DETALHE(RAT_UNIDADE, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS AUDITORIA (")
    AAdd(aLinhas, "    AUD_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    AUD_DATA_HORA DATETIME NOT NULL,")
    AAdd(aLinhas, "    AUD_TIPO TEXT NOT NULL,")
    AAdd(aLinhas, "    AUD_DESCRICAO TEXT,")
    AAdd(aLinhas, "    AUD_SEVERIDADE TEXT NOT NULL,")
    AAdd(aLinhas, "    AUD_RECNO_LAN NUMERIC,")
    AAdd(aLinhas, "    AUD_RECNO_COB NUMERIC,")
    AAdd(aLinhas, "    AUD_EXERCICIO TEXT,")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC,")
    AAdd(aLinhas, "    CHECK(AUD_SEVERIDADE IN ('CRITICA', 'AVISO', 'INFO')),")
    AAdd(aLinhas, "    CHECK(AUD_TIPO IN ('DESEQUILIBRIO_CONTABIL', 'COB_ORFAO', 'LAN_ORFAO', 'OUTRO'))")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_AUDITORIA_EXERCICIO ON AUDITORIA(AUD_EXERCICIO, AUD_SEVERIDADE, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS RPT_BALANCETE (")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    RPT_EXERCICIO TEXT NOT NULL,")
    AAdd(aLinhas, "    RPT_RECEITAS NUMERIC,")
    AAdd(aLinhas, "    RPT_DESPESAS NUMERIC,")
    AAdd(aLinhas, "    RPT_SALDO NUMERIC,")
    AAdd(aLinhas, "    RPT_DATA_GERACAO DATETIME,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC,")
    AAdd(aLinhas, "    UNIQUE(RPT_EXERCICIO, D_E_L_E_T_)")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para PLANO_CONTAS")
    AAdd(aLinhas, "DELETE FROM SX3 WHERE X3_ARQUIVO IN ('PLANO_CONTAS','REPARTICAO','EXERCICIO','LANCAMENTOS','RATEIO_DETALHE','AUDITORIA','RPT_BALANCETE');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('PLANO_CONTAS', 1, 'PLA_CODIGO', 'C', 10, 0, 'Código Conta'),")
    AAdd(aLinhas, "('PLANO_CONTAS', 2, 'PLA_NOME',   'C', 80, 0, 'Nome Conta'),")
    AAdd(aLinhas, "('PLANO_CONTAS', 3, 'PLA_TIPO',   'C', 15, 0, 'Tipo'),")
    AAdd(aLinhas, "('PLANO_CONTAS', 4, 'PLA_ATIVO',  'N',  1, 0, 'Ativo'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('REPARTICAO', 1, 'REP_CODIGO',   'C', 20, 0, 'Código Repartição'),")
    AAdd(aLinhas, "('REPARTICAO', 2, 'REP_NOME',     'C', 80, 0, 'Nome Repartição'),")
    AAdd(aLinhas, "('REPARTICAO', 3, 'REP_ATIVO',    'N',  1, 0, 'Ativo'),")
    AAdd(aLinhas, "('REPARTICAO', 4, 'REP_DETALHE',  'C', 200, 0, 'Detalhes'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('EXERCICIO', 1, 'EXE_CODIGO',   'C',  7, 0, 'Código Exercício'),")
    AAdd(aLinhas, "('EXERCICIO', 2, 'EXE_INICIO',   'D', 10, 0, 'Data Início'),")
    AAdd(aLinhas, "('EXERCICIO', 3, 'EXE_FIM',      'D', 10, 0, 'Data Fim'),")
    AAdd(aLinhas, "('EXERCICIO', 4, 'EXE_ATIVO',    'N',  1, 0, 'Ativo'),")
    AAdd(aLinhas, "('EXERCICIO', 5, 'EXE_FECHADO',  'N',  1, 0, 'Fechado'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('LANCAMENTOS', 1, 'LAN_DATA',       'D', 10, 0, 'Data Lançamento'),")
    AAdd(aLinhas, "('LANCAMENTOS', 2, 'LAN_CONTA_DEB',  'C', 10, 0, 'Conta Débito'),")
    AAdd(aLinhas, "('LANCAMENTOS', 3, 'LAN_CONTA_CRED', 'C', 10, 0, 'Conta Crédito'),")
    AAdd(aLinhas, "('LANCAMENTOS', 4, 'LAN_VALOR',      'N', 14, 2, 'Valor'),")
    AAdd(aLinhas, "('LANCAMENTOS', 5, 'LAN_DESCR',      'C', 200, 0, 'Descrição'),")
    AAdd(aLinhas, "('LANCAMENTOS', 6, 'LAN_TIPO',       'C', 20, 0, 'Tipo Lançamento'),")
    AAdd(aLinhas, "('LANCAMENTOS', 7, 'LAN_EXERCICIO',  'C',  7, 0, 'Exercício'),")
    AAdd(aLinhas, "('LANCAMENTOS', 8, 'LAN_DATA_HORA',  'C', 19, 0, 'Data/Hora'),")
    AAdd(aLinhas, "('LANCAMENTOS', 9, 'LAN_USUARIO',    'C', 40, 0, 'Usuário'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('RATEIO_DETALHE', 1, 'RAT_LANCAMENTO',  'N',  10, 0, 'ID Lançamento'),")
    AAdd(aLinhas, "('RATEIO_DETALHE', 2, 'RAT_UNIDADE',     'C',  10, 0, 'Unidade'),")
    AAdd(aLinhas, "('RATEIO_DETALHE', 3, 'RAT_VALOR',       'N',  14, 2, 'Valor Rateado'),")
    AAdd(aLinhas, "('RATEIO_DETALHE', 4, 'RAT_PERCENTUAL',  'N',   8, 4, 'Percentual'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('AUDITORIA', 1, 'AUD_DATA_HORA',   'C', 19, 0, 'Data/Hora'),")
    AAdd(aLinhas, "('AUDITORIA', 2, 'AUD_TIPO',        'C', 25, 0, 'Tipo Anomalia'),")
    AAdd(aLinhas, "('AUDITORIA', 3, 'AUD_DESCRICAO',   'C', 200, 0, 'Descrição'),")
    AAdd(aLinhas, "('AUDITORIA', 4, 'AUD_SEVERIDADE',  'C', 10, 0, 'Severidade'),")
    AAdd(aLinhas, "('AUDITORIA', 5, 'AUD_EXERCICIO',   'C',  7, 0, 'Exercício'),")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "('RPT_BALANCETE', 1, 'RPT_EXERCICIO',      'C',  7, 0, 'Exercício'),")
    AAdd(aLinhas, "('RPT_BALANCETE', 2, 'RPT_RECEITAS',       'N', 14, 2, 'Receitas'),")
    AAdd(aLinhas, "('RPT_BALANCETE', 3, 'RPT_DESPESAS',       'N', 14, 2, 'Despesas'),")
    AAdd(aLinhas, "('RPT_BALANCETE', 4, 'RPT_SALDO',          'N', 14, 2, 'Saldo'),")
    AAdd(aLinhas, "('RPT_BALANCETE', 5, 'RPT_DATA_GERACAO',   'C', 19, 0, 'Data Geração');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Seed data for accounting system")
    AAdd(aLinhas, "INSERT OR IGNORE INTO PLANO_CONTAS (PLA_CODIGO, PLA_NOME, PLA_TIPO, PLA_ATIVO)")
    AAdd(aLinhas, "VALUES")
    AAdd(aLinhas, "  ('1000', 'Caixa',                    'ATIVO',     1),")
    AAdd(aLinhas, "  ('1100', 'Banco',                    'ATIVO',     1),")
    AAdd(aLinhas, "  ('2000', 'Contas a Pagar',           'PASSIVO',   1),")
    AAdd(aLinhas, "  ('2100', 'Débitos Anteriores',       'PASSIVO',   1),")
    AAdd(aLinhas, "  ('3000', 'Receita Condominial',      'RECEITA',   1),")
    AAdd(aLinhas, "  ('3100', 'Multas e Juros',           'RECEITA',   1),")
    AAdd(aLinhas, "  ('4000', 'Despesa Comum',            'DESPESA',   1),")
    AAdd(aLinhas, "  ('4100', 'Despesa Extraordinária',   'DESPESA',   1),")
    AAdd(aLinhas, "  ('4200', 'Água/Luz/Condomínio',      'DESPESA',   1),")
    AAdd(aLinhas, "  ('4300', 'Limpeza',                  'DESPESA',   1),")
    AAdd(aLinhas, "  ('4400', 'Segurança',                'DESPESA',   1),")
    AAdd(aLinhas, "  ('4500', 'Manutenção',               'DESPESA',   1),")
    AAdd(aLinhas, "  ('4600', 'Seguros',                  'DESPESA',   1),")
    AAdd(aLinhas, "  ('4700', 'Impostos e Taxas',         'DESPESA',   1),")
    AAdd(aLinhas, "  ('4800', 'Depreciação',              'DESPESA',   1),")
    AAdd(aLinhas, "  ('4900', 'Ajustes e Créditos',       'DESPESA',   1),")
    AAdd(aLinhas, "  ('5000', 'Contas a Receber',         'ATIVO',     1),")
    AAdd(aLinhas, "  ('6000', 'Capital/Patrimônio',       'PASSIVO',   1),")
    AAdd(aLinhas, "  ('6100', 'Lucros Acumulados',        'PASSIVO',   1),")
    AAdd(aLinhas, "  ('7000', 'Outras Contas',            'ATIVO',     1);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "INSERT OR IGNORE INTO EXERCICIO (EXE_CODIGO, EXE_INICIO, EXE_FIM, EXE_ATIVO, EXE_FECHADO)")
    AAdd(aLinhas, "VALUES")
    AAdd(aLinhas, "  ('2025-01', '20250101', '20250131', 1, 0);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "INSERT OR IGNORE INTO REPARTICAO (REP_CODIGO, REP_NOME, REP_ATIVO)")
    AAdd(aLinhas, "VALUES")
    AAdd(aLinhas, "  ('FRACAO', 'Fração Ideal', 1),")
    AAdd(aLinhas, "  ('METRAGEM', 'Por Metragem', 1),")
    AAdd(aLinhas, "  ('FIXO', 'Valor Fixo', 1);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Seed units for testing")
    AAdd(aLinhas, "INSERT OR IGNORE INTO UNI (UNI_CODIGO, UNI_BLOCO, UNI_FRACAO)")
    AAdd(aLinhas, "VALUES")
    AAdd(aLinhas, "  ('101', 'A', 0.05),")
    AAdd(aLinhas, "  ('102', 'A', 0.05),")
    AAdd(aLinhas, "  ('103', 'B', 0.05),")
    AAdd(aLinhas, "  ('104', 'B', 0.05),")
    AAdd(aLinhas, "  ('105', 'C', 0.05),")
    AAdd(aLinhas, "  ('106', 'C', 0.05),")
    AAdd(aLinhas, "  ('107', 'D', 0.05),")
    AAdd(aLinhas, "  ('108', 'D', 0.05),")
    AAdd(aLinhas, "  ('109', 'E', 0.05),")
    AAdd(aLinhas, "  ('110', 'E', 0.05),")
    AAdd(aLinhas, "  ('111', 'F', 0.05),")
    AAdd(aLinhas, "  ('112', 'F', 0.05),")
    AAdd(aLinhas, "  ('113', 'G', 0.05),")
    AAdd(aLinhas, "  ('114', 'G', 0.05),")
    AAdd(aLinhas, "  ('115', 'H', 0.05),")
    AAdd(aLinhas, "  ('116', 'H', 0.05),")
    AAdd(aLinhas, "  ('117', 'I', 0.05),")
    AAdd(aLinhas, "  ('118', 'I', 0.05),")
    AAdd(aLinhas, "  ('119', 'J', 0.05),")
    AAdd(aLinhas, "  ('120', 'J', 0.05);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- ============================================================================")
    AAdd(aLinhas, "-- Portal do Condômino v2 — Tabelas de snapshot (avisos, extratos, agenda)")
    AAdd(aLinhas, "-- ============================================================================")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- AVISOS: Mural de avisos (anúncios publicados pelos admin)")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS AVISOS (")
    AAdd(aLinhas, "    AVI_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    AVI_TITULO TEXT NOT NULL,")
    AAdd(aLinhas, "    AVI_CORPO TEXT NOT NULL,")
    AAdd(aLinhas, "    AVI_DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,")
    AAdd(aLinhas, "    AVI_ATIVO INTEGER DEFAULT 1 CHECK(AVI_ATIVO IN (0, 1)),")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER UNIQUE,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_AVISOS_ATIVO ON AVISOS(AVI_ATIVO, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- RPT_PORTAL_EXTRATOS: Snapshot de faturas por unidade/mês")
    AAdd(aLinhas, "-- Regenerado 100% (DELETE + INSERT) a cada fechamento de período")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS RPT_PORTAL_EXTRATOS (")
    AAdd(aLinhas, "    REX_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    REX_COMPETENCIA TEXT NOT NULL,")
    AAdd(aLinhas, "    REX_UNIDADE TEXT NOT NULL,")
    AAdd(aLinhas, "    REX_VALOR NUMERIC NOT NULL,")
    AAdd(aLinhas, "    REX_VENCIMENTO DATE NOT NULL,")
    AAdd(aLinhas, "    REX_STATUS TEXT DEFAULT 'PENDENTE' CHECK(REX_STATUS IN ('PENDENTE', 'PAGO')),")
    AAdd(aLinhas, "    REX_DATA_PAGAMENTO DATE,")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER UNIQUE,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC,")
    AAdd(aLinhas, "    UNIQUE(REX_COMPETENCIA, REX_UNIDADE, D_E_L_E_T_),")
    AAdd(aLinhas, "    FOREIGN KEY(REX_UNIDADE) REFERENCES UNI(UNI_CODIGO)")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_RPT_PORTAL_EXTRATOS_UNIDADE ON RPT_PORTAL_EXTRATOS(REX_UNIDADE, D_E_L_E_T_);")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_RPT_PORTAL_EXTRATOS_COMPETENCIA ON RPT_PORTAL_EXTRATOS(REX_COMPETENCIA, D_E_L_E_T_);")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_RPT_PORTAL_EXTRATOS_STATUS ON RPT_PORTAL_EXTRATOS(REX_STATUS, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- RPT_PORTAL_AGENDA: Próximos vencimentos (próximos 12 meses)")
    AAdd(aLinhas, "-- Regenerado 100% (DELETE + INSERT) a cada fechamento de período")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS RPT_PORTAL_AGENDA (")
    AAdd(aLinhas, "    REA_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "    REA_UNIDADE TEXT NOT NULL,")
    AAdd(aLinhas, "    REA_COMPETENCIA TEXT NOT NULL,")
    AAdd(aLinhas, "    REA_VENCIMENTO DATE NOT NULL,")
    AAdd(aLinhas, "    REA_VALOR NUMERIC NOT NULL,")
    AAdd(aLinhas, "    R_E_C_N_O_ INTEGER UNIQUE,")
    AAdd(aLinhas, "    D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "    R_E_C_D_E_L_ NUMERIC,")
    AAdd(aLinhas, "    FOREIGN KEY(REA_UNIDADE) REFERENCES UNI(UNI_CODIGO)")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_RPT_PORTAL_AGENDA_UNIDADE ON RPT_PORTAL_AGENDA(REA_UNIDADE, D_E_L_E_T_);")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_RPT_PORTAL_AGENDA_VENCIMENTO ON RPT_PORTAL_AGENDA(REA_VENCIMENTO, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para AVISOS")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('AVISOS', 1, 'AVI_ID',            'N',  10, 0, 'ID Aviso'),")
    AAdd(aLinhas, "('AVISOS', 2, 'AVI_TITULO',        'C', 255, 0, 'Título'),")
    AAdd(aLinhas, "('AVISOS', 3, 'AVI_CORPO',         'M',   0, 0, 'Corpo'),")
    AAdd(aLinhas, "('AVISOS', 4, 'AVI_DATA_CRIACAO',  'C',  19, 0, 'Data Criação'),")
    AAdd(aLinhas, "('AVISOS', 5, 'AVI_ATIVO',         'N',   1, 0, 'Ativo');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para RPT_PORTAL_EXTRATOS")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('RPT_PORTAL_EXTRATOS', 1, 'REX_ID',              'N',  10, 0, 'ID Extrato'),")
    AAdd(aLinhas, "('RPT_PORTAL_EXTRATOS', 2, 'REX_COMPETENCIA',    'C',   7, 0, 'Competência'),")
    AAdd(aLinhas, "('RPT_PORTAL_EXTRATOS', 3, 'REX_UNIDADE',        'C',  10, 0, 'Unidade'),")
    AAdd(aLinhas, "('RPT_PORTAL_EXTRATOS', 4, 'REX_VALOR',          'N',  14, 2, 'Valor'),")
    AAdd(aLinhas, "('RPT_PORTAL_EXTRATOS', 5, 'REX_VENCIMENTO',     'D',  10, 0, 'Vencimento'),")
    AAdd(aLinhas, "('RPT_PORTAL_EXTRATOS', 6, 'REX_STATUS',         'C',  10, 0, 'Status'),")
    AAdd(aLinhas, "('RPT_PORTAL_EXTRATOS', 7, 'REX_DATA_PAGAMENTO', 'D',  10, 0, 'Data Pagamento');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para RPT_PORTAL_AGENDA")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('RPT_PORTAL_AGENDA', 1, 'REA_ID',          'N',  10, 0, 'ID Agenda'),")
    AAdd(aLinhas, "('RPT_PORTAL_AGENDA', 2, 'REA_UNIDADE',     'C',  10, 0, 'Unidade'),")
    AAdd(aLinhas, "('RPT_PORTAL_AGENDA', 3, 'REA_COMPETENCIA', 'C',   7, 0, 'Competência'),")
    AAdd(aLinhas, "('RPT_PORTAL_AGENDA', 4, 'REA_VENCIMENTO',  'D',  10, 0, 'Vencimento'),")
    AAdd(aLinhas, "('RPT_PORTAL_AGENDA', 5, 'REA_VALOR',       'N',  14, 2, 'Valor');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- ANOMALIA_LOG: histÃ³rico de anomalias detectadas")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS ANOMALIA_LOG (")
    AAdd(aLinhas, "  ANL_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "  ANL_TIPO TEXT NOT NULL,")
    AAdd(aLinhas, "  ANL_PERIODO TEXT NOT NULL,")
    AAdd(aLinhas, "  ANL_UNIDADE TEXT,")
    AAdd(aLinhas, "  ANL_VALOR NUMERIC,")
    AAdd(aLinhas, "  ANL_DESCRICAO TEXT,")
    AAdd(aLinhas, "  ANL_LANCAMENTO_ID INTEGER,")
    AAdd(aLinhas, "  ANL_COBRANCA_ID INTEGER,")
    AAdd(aLinhas, "  ANL_CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,")
    AAdd(aLinhas, "  ANL_RESOLVIDO_EM DATETIME,")
    AAdd(aLinhas, "  ANL_STATUS TEXT DEFAULT 'ABERTO' CHECK(ANL_STATUS IN ('ABERTO', 'RESOLVIDO', 'IGNORADO')),")
    AAdd(aLinhas, "  R_E_C_N_O_ INTEGER UNIQUE,")
    AAdd(aLinhas, "  D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "  R_E_C_D_E_L_ NUMERIC")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_ANOMALIA_TIPO ON ANOMALIA_LOG(ANL_TIPO, D_E_L_E_T_);")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_ANOMALIA_PERIODO ON ANOMALIA_LOG(ANL_PERIODO, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- ALERTA: notificaÃ§Ãµes crÃ­ticas em tempo real")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS ALERTA (")
    AAdd(aLinhas, "  ALT_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "  ALT_TIPO TEXT NOT NULL CHECK(ALT_TIPO IN ('CRITICO', 'AVISO', 'INFO')),")
    AAdd(aLinhas, "  ALT_ANOMALIA_ID INTEGER,")
    AAdd(aLinhas, "  ALT_MENSAGEM TEXT NOT NULL,")
    AAdd(aLinhas, "  ALT_CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,")
    AAdd(aLinhas, "  ALT_VISTO INTEGER DEFAULT 0,")
    AAdd(aLinhas, "  ALT_VISTO_EM DATETIME,")
    AAdd(aLinhas, "  R_E_C_N_O_ INTEGER UNIQUE,")
    AAdd(aLinhas, "  D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "  R_E_C_D_E_L_ NUMERIC,")
    AAdd(aLinhas, "  FOREIGN KEY(ALT_ANOMALIA_ID) REFERENCES ANOMALIA_LOG(ANL_ID)")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE INDEX IF NOT EXISTS IDX_ALERTA_TIPO ON ALERTA(ALT_TIPO, ALT_VISTO, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- DASHBOARD_CACHE: snapshot diÃ¡rio para performance")
    AAdd(aLinhas, "CREATE TABLE IF NOT EXISTS DASHBOARD_CACHE (")
    AAdd(aLinhas, "  DSH_ID INTEGER PRIMARY KEY AUTOINCREMENT,")
    AAdd(aLinhas, "  DSH_DATA DATE NOT NULL,")
    AAdd(aLinhas, "  DSH_PERIODO TEXT NOT NULL,")
    AAdd(aLinhas, "  DSH_ANOMALIAS_TOTAL NUMERIC,")
    AAdd(aLinhas, "  DSH_DESEQUILIBRIO_COUNT NUMERIC,")
    AAdd(aLinhas, "  DSH_LAN_ORFAO_COUNT NUMERIC,")
    AAdd(aLinhas, "  DSH_COB_ORFAO_COUNT NUMERIC,")
    AAdd(aLinhas, "  DSH_RATEIO_INVALID_COUNT NUMERIC,")
    AAdd(aLinhas, "  DSH_TIMING_COUNT NUMERIC,")
    AAdd(aLinhas, "  DSH_USUARIO_COUNT NUMERIC,")
    AAdd(aLinhas, "  DSH_JSON TEXT,")
    AAdd(aLinhas, "  DSH_ATUALIZADO_EM DATETIME,")
    AAdd(aLinhas, "  R_E_C_N_O_ INTEGER UNIQUE,")
    AAdd(aLinhas, "  D_E_L_E_T_ TEXT DEFAULT ' ',")
    AAdd(aLinhas, "  R_E_C_D_E_L_ NUMERIC")
    AAdd(aLinhas, ");")
    AAdd(aLinhas, "CREATE UNIQUE INDEX IF NOT EXISTS IDX_DASHBOARD_DATA_PERIODO ON DASHBOARD_CACHE(DSH_DATA, DSH_PERIODO, D_E_L_E_T_);")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- Metadados SX3 para TOK_PERFIL")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('GCT_TOKEN', 8, 'TOK_PERFIL', 'C', 20, 0, 'Perfil do Token');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- ============================================================================")
    AAdd(aLinhas, "-- Metadados SX3 das tabelas de auditoria (Portal v3)")
    AAdd(aLinhas, "-- Sem estas linhas o FWMBrowse abre ANOMALIA_LOG, ALERTA e DASHBOARD_CACHE")
    AAdd(aLinhas, "-- sem coluna nenhuma -- as telas do menu Auditoria dependem disto.")
    AAdd(aLinhas, "-- ============================================================================")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "DELETE FROM SX3 WHERE X3_ARQUIVO IN ('ANOMALIA_LOG','ALERTA','DASHBOARD_CACHE');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('ANOMALIA_LOG', 1, 'ANL_ID',            'N', 10, 0, 'ID'),")
    AAdd(aLinhas, "('ANOMALIA_LOG', 2, 'ANL_TIPO',          'C', 40, 0, 'Tipo'),")
    AAdd(aLinhas, "('ANOMALIA_LOG', 3, 'ANL_PERIODO',       'C',  7, 0, 'Período'),")
    AAdd(aLinhas, "('ANOMALIA_LOG', 4, 'ANL_UNIDADE',       'C', 20, 0, 'Unidade'),")
    AAdd(aLinhas, "('ANOMALIA_LOG', 5, 'ANL_VALOR',         'N', 14, 2, 'Valor'),")
    AAdd(aLinhas, "('ANOMALIA_LOG', 6, 'ANL_DESCRICAO',     'C',255, 0, 'Descrição'),")
    AAdd(aLinhas, "('ANOMALIA_LOG', 7, 'ANL_LANCAMENTO_ID', 'N', 10, 0, 'Lançamento'),")
    AAdd(aLinhas, "('ANOMALIA_LOG', 8, 'ANL_COBRANCA_ID',   'N', 10, 0, 'Cobrança'),")
    AAdd(aLinhas, "('ANOMALIA_LOG', 9, 'ANL_CRIADO_EM',     'C', 19, 0, 'Detectada em'),")
    AAdd(aLinhas, "('ANOMALIA_LOG',10, 'ANL_RESOLVIDO_EM',  'C', 19, 0, 'Resolvida em'),")
    AAdd(aLinhas, "('ANOMALIA_LOG',11, 'ANL_STATUS',        'C', 20, 0, 'Status');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('ALERTA', 1, 'ALT_ID',          'N', 10, 0, 'ID'),")
    AAdd(aLinhas, "('ALERTA', 2, 'ALT_TIPO',        'C', 20, 0, 'Tipo'),")
    AAdd(aLinhas, "('ALERTA', 3, 'ALT_ANOMALIA_ID', 'N', 10, 0, 'Anomalia'),")
    AAdd(aLinhas, "('ALERTA', 4, 'ALT_MENSAGEM',    'C',255, 0, 'Mensagem'),")
    AAdd(aLinhas, "('ALERTA', 5, 'ALT_CRIADO_EM',   'C', 19, 0, 'Criado em'),")
    AAdd(aLinhas, "('ALERTA', 6, 'ALT_VISTO',       'N',  1, 0, 'Visto'),")
    AAdd(aLinhas, "('ALERTA', 7, 'ALT_VISTO_EM',    'C', 19, 0, 'Visto em');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 1, 'DSH_ID',                  'N', 10, 0, 'ID'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 2, 'DSH_DATA',                'C', 10, 0, 'Data'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 3, 'DSH_PERIODO',             'C',  7, 0, 'Período'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 4, 'DSH_ANOMALIAS_TOTAL',     'N', 10, 0, 'Total'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 5, 'DSH_DESEQUILIBRIO_COUNT', 'N', 10, 0, 'Desequilíbrio'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 6, 'DSH_LAN_ORFAO_COUNT',     'N', 10, 0, 'Lanç. órfãos'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 7, 'DSH_COB_ORFAO_COUNT',     'N', 10, 0, 'Cobr. órfãs'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 8, 'DSH_RATEIO_INVALID_COUNT','N', 10, 0, 'Rateio inválido'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE', 9, 'DSH_TIMING_COUNT',        'N', 10, 0, 'Timing'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE',10, 'DSH_USUARIO_COUNT',       'N', 10, 0, 'Usuário'),")
    AAdd(aLinhas, "('DASHBOARD_CACHE',11, 'DSH_ATUALIZADO_EM',       'C', 19, 0, 'Atualizado em');")
    AAdd(aLinhas, "")
    AAdd(aLinhas, "-- USR_LOGIN faltava: o browse de usuarios abria com uma coluna so.")
    AAdd(aLinhas, "-- USR_SENHA fica fora de proposito -- hash nao se mostra em tela.")
    AAdd(aLinhas, "INSERT INTO SX3 (X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO) VALUES")
    AAdd(aLinhas, "('USR', 1, 'USR_LOGIN', 'C', 50, 0, 'Login');")

    For nI := 1 To Len(aLinhas)
        cSQL += aLinhas[nI] + Chr(10)
    Next nI
Return cSQL
